language: node_js

before_install:
  - npm install convict reflect-metadata

install:
  - NODE_ENV=dev npm install

before_script:
  - npm run lint

script:
  - npm test

before_deploy:
  - npm build:prod

deploy:
  provider: npm
  email: kelly@akirix.com
  api_key: $NPM_TOKEN
  on:
    tags: true